name: "HA RBAC"
description: "Graphical Role Based Access Control for Home Assistant"
version: "0.1.5"
slug: "ha_rbac"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000

# Panel configuration
ingress: true
ingress_port: 8000
# TODO only authorize IP 172.30.32.2 on the web server

panel_icon: "mdi:shield-lock"
panel_title: "Home Assistant RBAC"

# Security
homeassistant_api: true
# privileged:
#   - NET_ADMIN
#   - SYS_ADMIN
#   - SYS_RAWIO
#   - SYS_TIME
#   - SYS_NICE

map:
  - homeassistant_config:rw
