# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Role-Based Access Control Add-on"
  org.opencontainers.image.description: "Graphical Role Based Access Control for Home Assistant"
  org.opencontainers.image.source: "https://github.com/AxelROGET/HA_RBAC"
  org.opencontainers.image.licenses: "CC-BY-NC-SA-4.0"
