name: "HA RBAC"
description: "Graphical Role Based Access Control for Home Assistant"
version: "0.2.5"
slug: "ha_rbac"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000

# Panel configuration
ingress: true
ingress_port: 8000

panel_icon: "mdi:shield-lock"
panel_title: "Home Assistant RBAC"
panel_admin: true

# Security
homeassistant_api: true


map:
  - homeassistant_config:rw
image: "axelroget/image-{arch}-ha_rbac"
